storeapi.main - 13 - Hello wolrd
uvicorn.error - 62 - Application startup complete.
uvicorn.error - 215 - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
storeapi.routes.post - 12 - Finding post with ID: 0
storeapi.routes.post - 14 - SELECT posts.id, posts.body 
FROM posts 
WHERE posts.id = :id_1
uvicorn.access - 476 - 127.0.0.1:51355 - "GET /post/0 HTTP/1.1" 404
uvicorn.error - 263 - Shutting down
uvicorn.error - 67 - Waiting for application shutdown.
uvicorn.error - 76 - Application shutdown complete.
uvicorn.error - 93 - Finished server process [50874]
storeapi.main - 13 - Hello wolrd
uvicorn.error - 62 - Application startup complete.
uvicorn.error - 215 - Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
storeapi.routes.post - 56 - Getting post with ID
storeapi.routes.post - 12 - Finding post with ID: 0
storeapi.routes.post - 14 - SELECT posts.id, posts.body 
FROM posts 
WHERE posts.id = :id_1
storeapi.routes.post - 59 - Post with ID 0 not found
uvicorn.access - 476 - 127.0.0.1:51485 - "GET /post/0 HTTP/1.1" 404
(-)storeapi.main - 15 - Hello wolrd
(-)uvicorn.error - 62 - Application startup complete.
(03a6cd26)storeapi.routes.post - 27 - Getting all posts
(03a6cd26)storeapi.routes.post - 30 - SELECT posts.id, posts.body 
FROM posts
(03a6cd26)uvicorn.access - 476 - 127.0.0.1:50110 - "GET /post HTTP/1.1" 200
(-)uvicorn.error - 263 - Shutting down
(-)uvicorn.error - 67 - Waiting for application shutdown.
(-)uvicorn.error - 76 - Application shutdown complete.
(-)uvicorn.error - 93 - Finished server process [52614]
{"asctime": "2025-06-19 15:21:13", "msecs": 98.0, "levelname": "INFO", "correlation_id": "-", "name": "storeapi.main", "lineno": 15, "message": "Hello wolrd"}
{"asctime": "2025-06-19 15:21:13", "msecs": 100.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 62, "message": "Application startup complete."}
{"asctime": "2025-06-19 15:21:48", "msecs": 44.0, "levelname": "INFO", "correlation_id": "f29198ae", "name": "uvicorn.access", "lineno": 476, "message": "127.0.0.1:50498 - \"POST /post HTTP/1.1\" 201"}
{"asctime": "2025-06-19 15:26:07", "msecs": 564.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 263, "message": "Shutting down"}
{"asctime": "2025-06-19 15:26:07", "msecs": 688.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 67, "message": "Waiting for application shutdown."}
{"asctime": "2025-06-19 15:26:07", "msecs": 691.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 76, "message": "Application shutdown complete."}
{"asctime": "2025-06-19 15:26:07", "msecs": 692.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 93, "message": "Finished server process [53028]", "color_message": "Finished server process [\u001b[36m%d\u001b[0m]"}
{"asctime": "2025-06-23 15:21:54", "msecs": 342.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 895, in add_handlers\n    logger.addHandler(self.config['handlers'][h])\n                      ~~~~~~~~~~~~~~~~~~~~~~~^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 341, in __getitem__\n    value = dict.__getitem__(self, key)\nKeyError: 'logtail'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 658, in configure\n    self.configure_logger(name, loggers[name])\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 920, in configure_logger\n    self.common_logger_config(logger, config, incremental)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 912, in common_logger_config\n    self.add_handlers(logger, handlers)\n    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 897, in add_handlers\n    raise ValueError('Unable to add handler %r' % h) from e\nValueError: Unable to add handler 'logtail'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/routing.py\", line 692, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py\", line 214, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/fastapi/routing.py\", line 133, in merged_lifespan\n    async with original_context(app) as maybe_original_state:\n               ~~~~~~~~~~~~~~~~^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py\", line 214, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/fastapi/routing.py\", line 133, in merged_lifespan\n    async with original_context(app) as maybe_original_state:\n               ~~~~~~~~~~~~~~~~^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py\", line 214, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Apple/facepalm/storeapi/main.py\", line 15, in lifespan\n    configure_logging()\n    ~~~~~~~~~~~~~~~~~^^\n  File \"/Users/Apple/facepalm/storeapi/logging_conf.py\", line 28, in configure_logging\n    dictConfig(\n    ~~~~~~~~~~^\n        {\n        ^\n    ...<62 lines>...\n        }\n        ^\n    )\n    ^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 935, in dictConfig\n    dictConfigClass(config).configure()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 660, in configure\n    raise ValueError('Unable to configure logger '\n                     '%r' % name) from e\nValueError: Unable to configure logger 'storeapi'\n"}
{"asctime": "2025-06-23 15:21:54", "msecs": 348.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-06-23 15:23:59", "msecs": 752.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 121, "message": "Traceback (most recent call last):\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 895, in add_handlers\n    logger.addHandler(self.config['handlers'][h])\n                      ~~~~~~~~~~~~~~~~~~~~~~~^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 341, in __getitem__\n    value = dict.__getitem__(self, key)\nKeyError: 'console'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 658, in configure\n    self.configure_logger(name, loggers[name])\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 920, in configure_logger\n    self.common_logger_config(logger, config, incremental)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 912, in common_logger_config\n    self.add_handlers(logger, handlers)\n    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 897, in add_handlers\n    raise ValueError('Unable to add handler %r' % h) from e\nValueError: Unable to add handler 'console'\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/routing.py\", line 692, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n               ~~~~~~~~~~~~~~~~~~~~~^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py\", line 214, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/fastapi/routing.py\", line 133, in merged_lifespan\n    async with original_context(app) as maybe_original_state:\n               ~~~~~~~~~~~~~~~~^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py\", line 214, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/fastapi/routing.py\", line 133, in merged_lifespan\n    async with original_context(app) as maybe_original_state:\n               ~~~~~~~~~~~~~~~~^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py\", line 214, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Apple/facepalm/storeapi/main.py\", line 15, in lifespan\n    configure_logging()\n    ~~~~~~~~~~~~~~~~~^^\n  File \"/Users/Apple/facepalm/storeapi/logging_conf.py\", line 28, in configure_logging\n    dictConfig(\n    ~~~~~~~~~~^\n        {\n        ^\n    ...<62 lines>...\n        }\n        ^\n    )\n    ^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 935, in dictConfig\n    dictConfigClass(config).configure()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/config.py\", line 660, in configure\n    raise ValueError('Unable to configure logger '\n                     '%r' % name) from e\nValueError: Unable to configure logger 'storeapi'\n"}
{"asctime": "2025-06-23 15:23:59", "msecs": 760.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 59, "message": "Application startup failed. Exiting."}
{"asctime": "2025-06-23 15:24:20", "msecs": 612.0, "levelname": "INFO", "correlation_id": "-", "name": "storeapi.main", "lineno": 16, "message": "Hello wolrd"}
{"asctime": "2025-06-23 15:24:20", "msecs": 615.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 62, "message": "Application startup complete."}
{"asctime": "2025-06-23 15:24:20", "msecs": 617.0, "levelname": "ERROR", "correlation_id": "-", "name": "uvicorn.error", "lineno": 171, "message": "[Errno 48] error while attempting to bind on address ('127.0.0.1', 8000): address already in use"}
{"asctime": "2025-06-23 15:24:20", "msecs": 618.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 67, "message": "Waiting for application shutdown."}
{"asctime": "2025-06-23 15:24:20", "msecs": 619.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 76, "message": "Application shutdown complete."}
{"asctime": "2025-06-23 15:24:36", "msecs": 684.0, "levelname": "INFO", "correlation_id": "-", "name": "storeapi.main", "lineno": 16, "message": "Hello wolrd"}
{"asctime": "2025-06-23 15:24:36", "msecs": 686.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 62, "message": "Application startup complete."}
{"asctime": "2025-06-23 15:24:36", "msecs": 688.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 215, "message": "Uvicorn running on http://127.0.0.1:8010 (Press CTRL+C to quit)", "color_message": "Uvicorn running on \u001b[1m%s://%s:%d\u001b[0m (Press CTRL+C to quit)"}
{"asctime": "2025-06-23 15:24:39", "msecs": 900.0, "levelname": "INFO", "correlation_id": "9e1fa5cf", "name": "uvicorn.access", "lineno": 476, "message": "127.0.0.1:61921 - \"GET / HTTP/1.1\" 404"}
{"asctime": "2025-06-23 15:24:41", "msecs": 110.0, "levelname": "INFO", "correlation_id": "08ae0ba7", "name": "uvicorn.access", "lineno": 476, "message": "127.0.0.1:61921 - \"GET /favicon.ico HTTP/1.1\" 404"}
{"asctime": "2025-06-23 15:24:54", "msecs": 285.0, "levelname": "INFO", "correlation_id": "762e8f56", "name": "uvicorn.access", "lineno": 476, "message": "127.0.0.1:61936 - \"GET /docs HTTP/1.1\" 200"}
{"asctime": "2025-06-23 15:24:54", "msecs": 625.0, "levelname": "INFO", "correlation_id": "7d41f437", "name": "uvicorn.access", "lineno": 476, "message": "127.0.0.1:61936 - \"GET /openapi.json HTTP/1.1\" 200"}
{"asctime": "2025-06-23 15:26:00", "msecs": 496.0, "levelname": "INFO", "correlation_id": "ab0ae85b", "name": "uvicorn.access", "lineno": 476, "message": "127.0.0.1:61964 - \"POST /register HTTP/1.1\" 500"}
{"asctime": "2025-06-23 15:26:00", "msecs": 498.0, "levelname": "ERROR", "correlation_id": "ab0ae85b", "name": "uvicorn.error", "lineno": 414, "message": "Exception in ASGI application\n", "exc_info": "Traceback (most recent call last):\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py\", line 409, in run_asgi\n    result = await app(  # type: ignore[func-returns-value]\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        self.scope, self.receive, self.send\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py\", line 60, in __call__\n    return await self.app(scope, receive, send)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/fastapi/applications.py\", line 1054, in __call__\n    await super().__call__(scope, receive, send)\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/applications.py\", line 112, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/middleware/errors.py\", line 187, in __call__\n    raise exc\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/middleware/errors.py\", line 165, in __call__\n    await self.app(scope, receive, _send)\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/asgi_correlation_id/middleware.py\", line 90, in __call__\n    await self.app(scope, receive, handle_outgoing_request)\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/middleware/exceptions.py\", line 62, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/routing.py\", line 714, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/routing.py\", line 734, in app\n    await route.handle(scope, receive, send)\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/routing.py\", line 288, in handle\n    await self.app(scope, receive, send)\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/routing.py\", line 76, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/starlette/routing.py\", line 73, in app\n    response = await f(request)\n               ^^^^^^^^^^^^^^^^\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/fastapi/routing.py\", line 301, in app\n    raw_response = await run_endpoint_function(\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n    )\n    ^\n  File \"/Users/Apple/facepalm/venv/lib/python3.13/site-packages/fastapi/routing.py\", line 212, in run_endpoint_function\n    return await dependant.call(**values)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Apple/facepalm/storeapi/routes/user.py\", line 14, in register\n    if await get_user(user.email):\n       ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Apple/facepalm/storeapi/security.py\", line 44, in get_user\n    logger.debug(\"Fetching user from db\", extra={\"email\": email})\n    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/__init__.py\", line 1507, in debug\n    self._log(DEBUG, msg, args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/__init__.py\", line 1664, in _log\n    self.handle(record)\n    ~~~~~~~~~~~^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/__init__.py\", line 1680, in handle\n    self.callHandlers(record)\n    ~~~~~~~~~~~~~~~~~^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/__init__.py\", line 1736, in callHandlers\n    hdlr.handle(record)\n    ~~~~~~~~~~~^^^^^^^^\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/__init__.py\", line 1021, in handle\n    rv = self.filter(record)\n  File \"/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/__init__.py\", line 866, in filter\n    result = f.filter(record)\n  File \"/Users/Apple/facepalm/storeapi/logging_conf.py\", line 20, in filter\n    record.email = obfuscated(record.email, self.obfuscated_length)\n                   ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/Apple/facepalm/storeapi/logging_conf.py\", line 9, in obfuscated\n    return characters + (\"*\" * len(first)- obfuscated_length) + \"@\" + last\n                         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~\nTypeError: unsupported operand type(s) for -: 'str' and 'int'"}
{"asctime": "2025-06-23 15:28:34", "msecs": 984.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 263, "message": "Shutting down"}
{"asctime": "2025-06-23 15:28:35", "msecs": 90.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 67, "message": "Waiting for application shutdown."}
{"asctime": "2025-06-23 15:28:35", "msecs": 93.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 76, "message": "Application shutdown complete."}
{"asctime": "2025-06-23 15:28:35", "msecs": 94.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 93, "message": "Finished server process [19681]", "color_message": "Finished server process [\u001b[36m%d\u001b[0m]"}
{"asctime": "2025-06-23 15:28:38", "msecs": 86.0, "levelname": "INFO", "correlation_id": "-", "name": "storeapi.main", "lineno": 16, "message": "Hello wolrd"}
{"asctime": "2025-06-23 15:28:38", "msecs": 88.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 62, "message": "Application startup complete."}
{"asctime": "2025-06-23 15:28:38", "msecs": 90.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 215, "message": "Uvicorn running on http://127.0.0.1:8010 (Press CTRL+C to quit)", "color_message": "Uvicorn running on \u001b[1m%s://%s:%d\u001b[0m (Press CTRL+C to quit)"}
{"asctime": "2025-06-23 15:28:42", "msecs": 796.0, "levelname": "INFO", "correlation_id": "ba3004a7", "name": "uvicorn.access", "lineno": 476, "message": "127.0.0.1:62069 - \"GET /docs HTTP/1.1\" 200"}
{"asctime": "2025-06-23 15:28:43", "msecs": 179.0, "levelname": "INFO", "correlation_id": "b4335365", "name": "uvicorn.access", "lineno": 476, "message": "127.0.0.1:62069 - \"GET /openapi.json HTTP/1.1\" 200"}
{"asctime": "2025-06-23 15:28:59", "msecs": 268.0, "levelname": "DEBUG", "correlation_id": "67abad11", "name": "storeapi.security", "lineno": 44, "message": "Fetching user from db", "email": "en***********@gmail.com"}
{"asctime": "2025-06-23 15:28:59", "msecs": 549.0, "levelname": "DEBUG", "correlation_id": "67abad11", "name": "storeapi.routes.user", "lineno": 18, "message": "INSERT INTO users (email, password) VALUES (:email, :password)"}
{"asctime": "2025-06-23 15:28:59", "msecs": 553.0, "levelname": "INFO", "correlation_id": "67abad11", "name": "uvicorn.access", "lineno": 476, "message": "127.0.0.1:62113 - \"POST /register HTTP/1.1\" 201"}
{"asctime": "2025-06-23 15:30:03", "msecs": 300.0, "levelname": "DEBUG", "correlation_id": "8afcde57", "name": "storeapi.security", "lineno": 52, "message": "Authenticating user", "email": "en***********@gmail.com"}
{"asctime": "2025-06-23 15:30:03", "msecs": 302.0, "levelname": "DEBUG", "correlation_id": "8afcde57", "name": "storeapi.security", "lineno": 44, "message": "Fetching user from db", "email": "en***********@gmail.com"}
{"asctime": "2025-06-23 15:30:03", "msecs": 541.0, "levelname": "DEBUG", "correlation_id": "8afcde57", "name": "storeapi.security", "lineno": 30, "message": "Creating access token", "email": "en***********@gmail.com"}
{"asctime": "2025-06-23 15:30:03", "msecs": 543.0, "levelname": "INFO", "correlation_id": "8afcde57", "name": "uvicorn.access", "lineno": 476, "message": "127.0.0.1:62137 - \"POST /token HTTP/1.1\" 200"}
{"asctime": "2025-06-23 15:36:07", "msecs": 732.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 263, "message": "Shutting down"}
{"asctime": "2025-06-23 15:36:07", "msecs": 855.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 67, "message": "Waiting for application shutdown."}
{"asctime": "2025-06-23 15:36:07", "msecs": 860.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 76, "message": "Application shutdown complete."}
{"asctime": "2025-06-23 15:36:07", "msecs": 862.0, "levelname": "INFO", "correlation_id": "-", "name": "uvicorn.error", "lineno": 93, "message": "Finished server process [19919]", "color_message": "Finished server process [\u001b[36m%d\u001b[0m]"}
